---
- name: Restart Code Server
  become: true
  ansible.builtin.systemd:
    name: code-server@{{ code_server_user }}
    state: restarted

- name: Reload Code-Server Service
  become: true
  ansible.builtin.systemd:
    name: code-server@{{ code_server_user }}
    state: restarted
    daemon_reload: true
