---
galaxy_info:
  author: artis3n
  description: Install Code Server onto an Ubuntu server.
  license: MIT

  min_ansible_version: '2.14'

  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - ubuntu
    - server
    - development
    - dev

collections:
  - community.general
dependencies: []

argument_specs:
  main:
    options: {}
