---
- name: Remove Motd-News Service
  become: true
  ansible.builtin.file:
    path: /usr/lib/systemd/system/motd-news.service
    state: absent
  notify: Reload Systemd

- name: Remove Motd-News
  become: true
  ansible.builtin.file:
    path: /etc/update-motd.d/50-motd-news
    state: absent

- name: Check if Apt-News is Disabled
  check_mode: true
  register: apt_news
  ansible.builtin.lineinfile:
    path: /etc/ubuntu-advantage/uaclient.conf
    regexp: '^\s*apt_news:'
    line: '  apt_news: false'
    state: present

- name: Disable Apt-News  # noqa: no-handler
  become: true
  register: disable_apt_news
  when: (apt_news is changed) or (apt_news is failed)
  changed_when: disable_apt_news.rc != 0
  ansible.builtin.command: pro config set apt_news=false
