---
- name: Remove Motd-News Service
  become: true
  ansible.builtin.file:
    path: /usr/lib/systemd/system/motd-news.service
    state: absent
  notify: Reload Systemd

- name: Remove Motd-News
  become: true
  ansible.builtin.file:
    path: /etc/update-motd.d/50-motd-news
    state: absent

- name: Get Ubuntu Advantage Config
  become: true
  register: ua_config
  ansible.builtin.slurp:
    src: /var/lib/ubuntu-advantage/user-config.json

- name: Parse Ubuntu Advantage Config
  become: true
  ansible.builtin.set_fact:
    ua_config_parsed: "{{ ua_config.content | b64decode | from_json }}"

- name: Get Apt-News Status
  become: true
  register: apt_news
  ansible.builtin.set_fact:
    apt_news: "{{ ua_config_parsed.apt_news }}"

- name: Disable Apt-News
  become: true
  register: disable_apt_news
  when: apt_news | bool
  ansible.builtin.command: pro config set apt_news=False
  changed_when: disable_apt_news.rc == 0
