---
name: Molecule Tests

on:
  pull_request:
    branches:
      - main

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependency manager
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install packages
        run: poetry install --no-interaction

      - name: Lint
        run: make lint

  molecule:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        molecule_test:
          - test-canonical-ads
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install dependency manager
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'poetry'

      - name: Install packages
        run: poetry install --no-interaction

      - name: Run scenario
        # Move project to ansible-required path to discover collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/artis3n/homelab
          cp -r ./ ~/.ansible/collections/ansible_collections/artis3n/homelab
          make ${{ matrix.molecule_test }}
