---
name: Molecule Tests

on:
  pull_request:
    branches:
      - main

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  lint:
    # Molecule, cgroupsv2 and systemd errors when run on ubuntu 22.04
    # but current molecule.yml croupsv2 configurations are fine on 20.04
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependency manager
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install packages
        run: poetry install --no-interaction

      - name: Lint
        run: make lint

  molecule:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependency manager
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'poetry'

      - name: Install packages
        run: poetry install --no-interaction

      - name: Run scenarios
        # Move project to ansible-requiered path to discover collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/artis3n/homelab
          cp -r ./ ~/.ansible/collections/ansible_collections/artis3n/homelab
          make test
